# Generated by Django 6.1 on 2026-09-08 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cargar_clientes'),
        ('liberaciones', '0006_limpiar_numeros_legacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionScrap',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'clasificaciones_scrap',
            },
        ),
        migrations.CreateModel(
            name='DefectoScrap',
            fields=[
                ('id_defecto_scrap', models.AutoField(primary_key=True, serialize=False)),
                ('defecto', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'defectos_scrap',
            },
        ),
        migrations.CreateModel(
            name='EstatusScrap',
            fields=[
                ('id_estatus_scrap', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_status', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estatus_scrap',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id_operador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'operadores',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id_supervisor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'supervisores',
            },
        ),
        migrations.CreateModel(
            name='TipoAcero',
            fields=[
                ('id_tipo_acero', models.AutoField(primary_key=True, serialize=False)),
                ('especificacion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipos_acero',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_turno', models.CharField(max_length=25, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'turnos',
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_parte', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_retrabajado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_ng', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clasificacion', models.ForeignKey(db_column='id_clasificacion', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to='scrap.clasificacionscrap')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to='clientes.cliente')),
                ('defecto', models.ForeignKey(db_column='id_defecto_scrap', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to='scrap.defectoscrap')),
                ('estatus', models.ForeignKey(db_column='id_estatus_scrap', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to='scrap.estatusscrap')),
                ('maquina', models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to='liberaciones.maquina')),
                ('operador', models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to='scrap.operador')),
                ('tipo_laminacion', models.ForeignKey(db_column='id_tipo_laminacion', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to='liberaciones.tipolaminacion')),
                ('usuario_registro', models.ForeignKey(db_column='usuario_registro_id', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(db_column='id_supervisor', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to='scrap.supervisor')),
                ('tipo_acero', models.ForeignKey(db_column='id_tipo_acero', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to='scrap.tipoacero')),
                ('turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.PROTECT, related_name='registros_scrap', to='scrap.turno')),
            ],
            options={
                'db_table': 'scrap',
            },
        ),
    ]
