# Generated by Django 6.1 on 2026-08-26 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0002_cargar_areas_iniciales'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categorias', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id_defecto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'defectos',
            },
        ),
        migrations.CreateModel(
            name='EstatusReclamacion',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_status', models.CharField(max_length=100, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'estatus_reclamaciones',
            },
        ),
        migrations.CreateModel(
            name='Ocurrencia',
            fields=[
                ('id_ocurrencia', models.AutoField(primary_key=True, serialize=False)),
                ('ocurrencia', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ocurrencias',
            },
        ),
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_reporte_cliente', models.CharField(max_length=50, unique=True)),
                ('issue', models.CharField(max_length=500)),
                ('numero_parte', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_contenedor', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen_defecto', models.ImageField(blank=True, null=True, upload_to='reclamaciones/defectos/')),
                ('causa_raiz', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateField()),
                ('fecha_confirmacion', models.DateField(blank=True, null=True)),
                ('fecha_contencion', models.DateField(blank=True, null=True)),
                ('fecha_CR_AC', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('dias_retrazo_al_reclamo', models.IntegerField(default=0)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo_cierre_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('areas_involucradas', models.ManyToManyField(blank=True, related_name='reclamaciones', to='areas.area')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones', to='reclamaciones.categoria')),
                ('cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamaciones', to='clientes.cliente')),
                ('defecto', models.ForeignKey(db_column='id_defecto', on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones', to='reclamaciones.defecto')),
                ('estatus', models.ForeignKey(db_column='id_estatus', on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones', to='reclamaciones.estatusreclamacion')),
                ('ocurrencia', models.ForeignKey(db_column='id_ocurrencia', on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones', to='reclamaciones.ocurrencia')),
            ],
            options={
                'db_table': 'reclamaciones',
            },
        ),
    ]
