# Generated by Django 6.1 on 2026-08-31 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusLiberacion',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_status', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estatus_liberaciones',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'maquinas',
            },
        ),
        migrations.CreateModel(
            name='TipoLaminacion',
            fields=[
                ('id_tipo_laminacion', models.AutoField(primary_key=True, serialize=False)),
                ('especificacion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipos_laminacion',
            },
        ),
        migrations.CreateModel(
            name='Liberacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=300)),
                ('fecha_liberacion', models.DateField()),
                ('hora_liberacion', models.TimeField()),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to='clientes.cliente')),
                ('estatus', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to='liberaciones.estatusliberacion')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to='liberaciones.maquina')),
                ('tipo_laminacion', models.ForeignKey(db_column='id_tipo_laminacion', on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to='liberaciones.tipolaminacion')),
            ],
            options={
                'db_table': 'liberaciones',
            },
        ),
    ]
