# Generated by Django 6.1 on 2026-08-31 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('liberaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberacion',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='liberacion',
            name='tipo_laminacion',
            field=models.ForeignKey(blank=True, db_column='id_tipo_laminacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to='liberaciones.tipolaminacion'),
        ),
    ]
