# Generated by Django 6.1.1 on 2026-09-25 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cargar_clientes'),
        ('liberaciones', '0006_limpiar_numeros_legacy'),
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tira_Liberacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_tira', models.ImageField(blank=True, null=True, upload_to='tiras_liberadas/')),
                ('Tipo_acero', models.ForeignKey(db_column='id_tipo_acero', on_delete=django.db.models.deletion.PROTECT, related_name='tiras_liberadas', to='scrap.tipoacero')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='tiras_liberadas', to='clientes.cliente')),
                ('tipo_laminacion', models.ForeignKey(db_column='id_tipo_laminacion', on_delete=django.db.models.deletion.PROTECT, related_name='tiras_liberadas', to='liberaciones.tipolaminacion')),
            ],
            options={
                'db_table': 'tiras_liberadas',
            },
        ),
    ]
