# Generated by Django 6.1 on 2026-08-26 18:43

from django.db import migrations


def crear_roles(apps, schema_editor):
    Rol = apps.get_model('usuarios', 'Rol')

    roles = [
        (1, 'ADMIN'),
        (2, 'ENCARGADO'),
        (3, 'USUARIO GENERAL'),
        (4, 'AUDITOR'),
    ]

    for rol_id, nombre in roles:
        Rol.objects.update_or_create(
            id=rol_id,
            defaults={'nombre': nombre}
        )


def eliminar_roles(apps, schema_editor):
    Rol = apps.get_model('usuarios', 'Rol')

    Rol.objects.filter(
        id__in=[1, 2, 3, 4]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            crear_roles,
            eliminar_roles
        ),
    ]