# Generated by Django 6.1 on 2026-08-26 18:53

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cargar_roles_iniciales'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puede_ver_Reclamaciones_int',
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_ver_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
