# Generated by Django 6.1 on 2026-09-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_managers_remove_usuario_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='puede_ver_reclamaciones',
            new_name='puede_gestionar_reclamaciones',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='puede_ver_reportes',
            new_name='puede_gestionar_reportes',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='puede_ver_scrap',
            new_name='puede_gestionar_scrap',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='puede_ver_tickets',
            new_name='puede_gestionar_reclamaciones_internas',
        ),
    ]
