# Generated by Django 6.1.1 on 2026-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_puede_ver_reclamaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puede_gestionar_targetas_viajeras',
            field=models.BooleanField(default=False),
        ),
    ]
