# Generated by Django 6.1.1 on 2026-09-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cargar_clientes'),
        ('liberaciones', '0007_tira_liberacion'),
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espesor',
            fields=[
                ('id_espesor', models.AutoField(primary_key=True, serialize=False)),
                ('espesor', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
            ],
            options={
                'db_table': 'espesores',
            },
        ),
        migrations.CreateModel(
            name='NumeroParteCliente',
            fields=[
                ('id_num_pcli', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'numero_parte_cliente',
            },
        ),
        migrations.CreateModel(
            name='StatusTar',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'status_tar',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_orden_trabajo', models.CharField(max_length=20)),
                ('lote', models.CharField(max_length=100)),
                ('numero_orden_compra', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='clientes.cliente')),
                ('espesor', models.ForeignKey(db_column='id_espesor', on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='tarj_viajeras.espesor')),
                ('laminacion', models.ForeignKey(db_column='id_laminacion', on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='liberaciones.tipolaminacion')),
                ('material', models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='scrap.tipoacero')),
                ('numero_parte_cliente', models.ForeignKey(db_column='id_num_pcli', on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='tarj_viajeras.numeropartecliente')),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
        migrations.CreateModel(
            name='TarjetaViajera',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_tarjeta', models.IntegerField()),
                ('sufijo', models.CharField(blank=True, max_length=1, null=True)),
                ('numero_alambres', models.IntegerField(blank=True, null=True)),
                ('piezas_por_alambre', models.IntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tara', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('produccion', models.ForeignKey(db_column='id_produccion', on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas_viajeras', to='tarj_viajeras.produccion')),
                ('status', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas_viajeras', to='tarj_viajeras.statustar')),
            ],
            options={
                'db_table': 'tarjetas_viajeras',
                'constraints': [models.UniqueConstraint(fields=('numero_tarjeta', 'sufijo'), name='uq_numero_tarjeta_sufijo')],
            },
        ),
    ]
