# Generated by Django 6.1 on 2026-08-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0002_cargar_areas_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusReclamacionInterna',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estatus_reclamaciones_internas',
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prioridad', models.AutoField(primary_key=True, serialize=False)),
                ('Prioridad', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('dias_resolucion', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'prioridades',
            },
        ),
        migrations.CreateModel(
            name='ReclamacionInterna',
            fields=[
                ('id_folio', models.AutoField(primary_key=True, serialize=False)),
                ('emisor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('dias_retraso', models.IntegerField(default=0)),
                ('evidencia_resolucion', models.TextField(blank=True, null=True)),
                ('problematica', models.TextField(blank=True, null=True)),
                ('accion_correctiva', models.TextField(blank=True, null=True)),
                ('area_responsable', models.ForeignKey(blank=True, db_column='id_area_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamaciones_internas', to='areas.area')),
                ('estatus', models.ForeignKey(db_column='id_estatus', on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones_internas', to='reclamaciones_internas.estatusreclamacioninterna')),
                ('prioridad', models.ForeignKey(blank=True, db_column='id_prioridad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamaciones_internas', to='reclamaciones_internas.prioridad')),
                ('usuario_creador', models.ForeignKey(db_column='id_usuario_creador', on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones_internas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reclamaciones_internas',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaReclamacionInterna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='reclamaciones_internas/evidencias/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reclamacion', models.ForeignKey(db_column='id_reclamacion_interna', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='reclamaciones_internas.reclamacioninterna')),
            ],
            options={
                'db_table': 'reclamaciones_internas_evidencias',
            },
        ),
    ]
