# Generated by Django 6.1 on 2026-08-27 00:03
from django.db import migrations


def crear_estatus(apps, schema_editor):
    Estatus = apps.get_model(
        'reclamaciones_internas',
        'EstatusReclamacionInterna'
    )

    estatus = [
        (1, 'Sin atender'),
        (2, 'En proceso'),
        (3, 'Pendiente de validación'),
        (4, 'Cerrado'),
    ]

    for estatus_id, descripcion in estatus:
        Estatus.objects.update_or_create(
            id_estatus=estatus_id,
            defaults={
                'descripcion': descripcion
            }
        )


def eliminar_estatus(apps, schema_editor):
    Estatus = apps.get_model(
        'reclamaciones_internas',
        'EstatusReclamacionInterna'
    )

    Estatus.objects.filter(
        id_estatus__in=[1, 2, 3, 4]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            'reclamaciones_internas',
            '0001_initial'
        ),
    ]

    operations = [
        migrations.RunPython(
            crear_estatus,
            eliminar_estatus
        ),
    ]