# Generated by Django 6.1.1 on 2026-09-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones_internas', '0007_formato_publicacion_y_editable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formatoreclamacioninterna',
            options={'ordering': ['-fecha_publicacion', '-actualizado_at']},
        ),
    ]
